status = [
    'Run tests',
    'Run rustfmt',
    'Run rustdoc',
    'Run clippy',
    'Run cargo deny (bans licenses sources)'
]
delete_merged_branches = true
required_approvals = 1
timeout_sec = 7200
up_to_date_approvals = true
use_squash_merge = true
